-- Create table for users
DROP DATABASE IF EXISTS mvc;
CREATE DATABASE mvc;
USE DATABASE mvc;
DROP TABLE IF EXISTS posts;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY, -- Change SERIAL to INT AUTO_INCREMENT
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);


-- Create table for posts

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY, -- Change SERIAL to INT AUTO_INCREMENT
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (author_id) REFERENCES users(id)
);
